### PR TITLE
Abstractify old webkit api

### PR DESCRIPTION
**Pull request by atsushieno**
As part of discussion at https://github.com/xamarin/xamarin-android/pull/1078#issuecomment-365187452 ,
we decided to make changes to those inconsistent methods that used to be
virtual and then became abstract, to become abstract even in old API level.

It is done at metadata fixup level.

(copying the commitmsg from https://github.com/xamarin/xamarin-android/pull/1304)

### CODE REVIEW

**Comment by atsushieno** [comment]
rebased onto the latest master.

**Comment by jonpryor** [comment]
@atsushieno: Do you have the HTML-based API diff handy?

**Comment by atsushieno** [comment]
Not an exact output, but it is on what my changes are based (reported as inter-api diff between 8.0 and 8.1 as I didn't waste time on building everything on master):

	<h1>### API BREAK BETWEEN v8.0 and v8.1</h1>
	 <div> 
	<h2>Namespace Android.Webkit</h2>
	 <div>
	<h3>Type Changed: Android.Webkit.WebHistoryItem</h3>
	<p>Modified properties:</p>
	<pre>
	<div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> int Id { get; }
	</div></pre>

	</div> 
	 <div>
	<h3>Type Changed: Android.Webkit.WebSettings</h3>
	<p>Modified properties:</p>
	<pre>
	<div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> bool NavDump { get; set; }
	</div><div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> bool PluginsEnabled { get; set; }
	</div><div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> string PluginsPath { get; set; }
	</div><div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> bool UseDoubleTree { get; set; }
	</div><div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> bool UseWebViewBackgroundForOverscrollBackground { get; set; }
	</div><div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> int UserAgent { get; set; }
	</div></pre>
	<p>Modified methods:</p>
	<pre>
	<div data-is-breaking>	public <span class='added added-breaking-inline'>abstract</span> WebSettings.TextSize GetTextSize ()
	</div></pre>

	</div> 

	</div> 
	Makefile:122: recipe for target 'check-inter-api-level' failed

**Comment by jonpryor** [comment]
Context: https://github.com/xamarin/xamarin-android/pull/1304

**Comment by atsushieno** [comment]
Closing as per https://github.com/xamarin/xamarin-android/pull/1304#issuecomment-368398635

**Pull request closed without merging**
